// Generated by Schem -- CLOCKED DIGITAL evaluation of "memseq"
// Derived from the Circuit IR; the .schem schematic is the source.
// 9 node(s), 0 relay(s), 0 tri-state buffer(s), 1 memory(ies); 7 clock cycle(s).
// Sequential boolean eval, state carried across cycles (verified == the engine).
const std = @import("std");
const N: usize = 9; const NR: usize = 0; const NSE: usize = 0; const NV: usize = 1; const NS: usize = 6; const NB: usize = 0;
const CYCLES: usize = 7;
const vcc = [1]usize{1};
const sw_a = [6]usize{1, 1, 1, 1, 1, 1}; const sw_b = [6]usize{2, 3, 4, 5, 8, 9};
var sw_state = [NS]bool{false, false, false, false, false, false};
// memory M: 4 words x 2 bits, mode ram
var m0_cells = [_][2]bool{[_]bool{false} ** 2} ** 4;
var m0_out = [_]bool{false} ** 2;
var m0_prevclk: bool = false;
var m0_wrote: bool = false;
var high = [_]bool{false} ** (N + 1);

fn relax(a: usize, b: usize) bool {
    if (high[a] and !high[b] and b != 0) { high[b] = true; return true; }
    if (high[b] and !high[a] and a != 0) { high[a] = true; return true; }
    return false;
}
fn reach() void {
    for (&high) |*h| h.* = false;
    for (vcc) |v| high[v] = true;
    if (m0_out[0]) high[6] = true;
    if (m0_out[1]) high[7] = true;
    var changed = true;
    while (changed) {
        changed = false;
        { var e: usize = 0; while (e < NS) : (e += 1) { if (sw_state[e]) { if (relax(sw_a[e], sw_b[e])) changed = true; } } }
        if (m0_out[0] and !high[6] and 6 != 0) { high[6] = true; changed = true; }
        if (m0_out[1] and !high[7] and 7 != 0) { high[7] = true; changed = true; }
    }
    high[0] = false;
}
fn settle() void {
    var pass: usize = 0;
    while (pass < 1000) : (pass += 1) {
        reach();
        var changed = false;
        _ = &changed;   // (buffers/reads settle within reach(); relays/memory may set this)
        const relays_stable = !changed;
        { var addr: usize = 0;
          if (high[2]) addr |= 1;
          if (high[3]) addr |= 2;
          const clkH = high[9]; const weH = high[8];
          if (relays_stable and !m0_wrote and clkH and weH and !m0_prevclk) {
              m0_cells[addr][0] = high[4];
              m0_cells[addr][1] = high[5];
              m0_wrote = true; changed = true;
          }
          if (m0_out[0] != m0_cells[addr][0]) { m0_out[0] = m0_cells[addr][0]; changed = true; }
          if (m0_out[1] != m0_cells[addr][1]) { m0_out[1] = m0_cells[addr][1]; changed = true; }
        }
        if (!changed) break;
    }
    m0_prevclk = high[9];
}

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("clocked digital \"memseq\" (1=HIGH, 0=LOW), 7 cycle(s)\n", .{});
    var cycle: usize = 0;
    while (cycle < CYCLES) : (cycle += 1) {
        // timed stimulus (-events): operate the panel each cycle
        if (cycle == 0) sw_state[0] = true; // close S_A0
        if (cycle == 0) sw_state[3] = true; // close S_DI1
        if (cycle == 0) sw_state[4] = true; // close S_WE
        if (cycle == 1) sw_state[5] = true; // close S_CLK
        if (cycle == 2) sw_state[5] = false; // open S_CLK
        if (cycle == 2) sw_state[4] = false; // open S_WE
        if (cycle == 2) sw_state[3] = false; // open S_DI1
        if (cycle == 3) sw_state[0] = false; // open S_A0
        if (cycle == 3) sw_state[2] = true; // close S_DI0
        if (cycle == 3) sw_state[4] = true; // close S_WE
        if (cycle == 4) sw_state[5] = true; // close S_CLK
        if (cycle == 5) sw_state[5] = false; // open S_CLK
        if (cycle == 5) sw_state[4] = false; // open S_WE
        if (cycle == 5) sw_state[2] = false; // open S_DI0
        if (cycle == 6) sw_state[0] = true; // close S_A0
        m0_wrote = false;
        settle();
        try stdout.print("cycle {d}:", .{cycle});
        try stdout.print(" N1={d}", .{@intFromBool(high[1])});
        try stdout.print(" N2={d}", .{@intFromBool(high[2])});
        try stdout.print(" N3={d}", .{@intFromBool(high[3])});
        try stdout.print(" N4={d}", .{@intFromBool(high[4])});
        try stdout.print(" N5={d}", .{@intFromBool(high[5])});
        try stdout.print(" N6={d}", .{@intFromBool(high[6])});
        try stdout.print(" N7={d}", .{@intFromBool(high[7])});
        try stdout.print(" N8={d}", .{@intFromBool(high[8])});
        try stdout.print(" N9={d}", .{@intFromBool(high[9])});
        try stdout.print("\n", .{});
    }
}
