// Generated by Schem -- CLOCKED DIGITAL evaluation of "cpu"
// Derived from the Circuit IR; the .schem schematic is the source.
// 45 node(s), 17 relay(s), 6 tri-state buffer(s), 1 memory(ies); 23 clock cycle(s).
// Sequential boolean eval, state carried across cycles (verified == the engine).
const std = @import("std");
const N: usize = 45; const NR: usize = 17; const NSE: usize = 0; const NV: usize = 1; const NS: usize = 8; const NB: usize = 6;
const CYCLES: usize = 23;
const vcc = [1]usize{1};
const b_in = [6]usize{13, 42, 27, 43, 35, 36}; const b_oe = [6]usize{39, 41, 39, 41, 39, 39}; const b_out = [6]usize{31, 31, 32, 32, 44, 45};
const sw_a = [8]usize{1, 1, 1, 1, 1, 1, 1, 1}; const sw_b = [8]usize{2, 39, 42, 43, 33, 34, 37, 38};
var sw_state = [NS]bool{false, false, false, false, false, false, false, false};
const r_c1 = [17]usize{2, 5, 7, 6, 2, 6, 14, 13, 5, 19, 21, 20, 5, 20, 28, 27, 39}; const r_c2 = [17]usize{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
const r_com = [17]usize{1, 4, 8, 1, 1, 11, 15, 1, 1, 18, 22, 1, 1, 25, 29, 1, 1}; const r_no = [17]usize{3, 6, 9, 8, 11, 13, 16, 15, 17, 20, 23, 22, 25, 27, 30, 29, 40}; const r_nc = [17]usize{4, 7, 6, 10, 12, 14, 13, 5, 18, 21, 20, 24, 26, 28, 27, 19, 41};
var energized = [_]bool{false} ** NR;
// memory M: 4 words x 2 bits, mode ram
var m0_cells = [_][2]bool{[_]bool{false} ** 2} ** 4;
var m0_out = [_]bool{false} ** 2;
var m0_prevclk: bool = false;
var m0_wrote: bool = false;
var high = [_]bool{false} ** (N + 1);

fn relax(a: usize, b: usize) bool {
    if (high[a] and !high[b] and b != 0) { high[b] = true; return true; }
    if (high[b] and !high[a] and a != 0) { high[a] = true; return true; }
    return false;
}
fn reach() void {
    for (&high) |*h| h.* = false;
    for (vcc) |v| high[v] = true;
    if (m0_out[0]) high[35] = true;
    if (m0_out[1]) high[36] = true;
    var changed = true;
    while (changed) {
        changed = false;
        { var e: usize = 0; while (e < NS) : (e += 1) { if (sw_state[e]) { if (relax(sw_a[e], sw_b[e])) changed = true; } } }
        { var r: usize = 0; while (r < NR) : (r += 1) {
            const t = if (energized[r]) r_no[r] else r_nc[r];
            if (relax(r_com[r], t)) changed = true;
        } }
        { var b: usize = 0; while (b < NB) : (b += 1) {   // tri-state: drive out=1 when enabled and in=1
            if (high[b_oe[b]] and high[b_in[b]] and !high[b_out[b]] and b_out[b] != 0) { high[b_out[b]] = true; changed = true; }
        } }
        if (m0_out[0] and !high[35] and 35 != 0) { high[35] = true; changed = true; }
        if (m0_out[1] and !high[36] and 36 != 0) { high[36] = true; changed = true; }
    }
    high[0] = false;
}
fn settle() void {
    var pass: usize = 0;
    while (pass < 1000) : (pass += 1) {
        reach();
        var changed = false;
        _ = &changed;   // (buffers/reads settle within reach(); relays/memory may set this)
        { var r: usize = 0; while (r < NR) : (r += 1) {
            const en = high[r_c1[r]] != high[r_c2[r]];
            if (en != energized[r]) { energized[r] = en; changed = true; }
        } }
        { var addr: usize = 0;
          if (high[31]) addr |= 1;
          if (high[32]) addr |= 2;
          const clkH = high[38]; const weH = high[37];
          if (relays_stable and !m0_wrote and clkH and weH and !m0_prevclk) {
              m0_cells[addr][0] = high[33];
              m0_cells[addr][1] = high[34];
              m0_wrote = true; changed = true;
          }
          if (m0_out[0] != m0_cells[addr][0]) { m0_out[0] = m0_cells[addr][0]; changed = true; }
          if (m0_out[1] != m0_cells[addr][1]) { m0_out[1] = m0_cells[addr][1]; changed = true; }
        }
        if (!changed) break;
    }
    m0_prevclk = high[38];
}

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("clocked digital \"cpu\" (1=HIGH, 0=LOW), 23 cycle(s)\n", .{});
    var cycle: usize = 0;
    while (cycle < CYCLES) : (cycle += 1) {
        // timed stimulus (-events): operate the panel each cycle
        if (cycle == 0) sw_state[4] = true; // close LD0
        if (cycle == 0) sw_state[6] = true; // close WE
        if (cycle == 1) sw_state[7] = true; // close WCLK
        if (cycle == 2) sw_state[7] = false; // open WCLK
        if (cycle == 3) sw_state[2] = true; // close LA0
        if (cycle == 3) sw_state[4] = false; // open LD0
        if (cycle == 3) sw_state[5] = true; // close LD1
        if (cycle == 4) sw_state[7] = true; // close WCLK
        if (cycle == 5) sw_state[7] = false; // open WCLK
        if (cycle == 6) sw_state[2] = false; // open LA0
        if (cycle == 6) sw_state[3] = true; // close LA1
        if (cycle == 6) sw_state[4] = true; // close LD0
        if (cycle == 7) sw_state[7] = true; // close WCLK
        if (cycle == 8) sw_state[7] = false; // open WCLK
        if (cycle == 9) sw_state[2] = true; // close LA0
        if (cycle == 9) sw_state[4] = false; // open LD0
        if (cycle == 9) sw_state[5] = false; // open LD1
        if (cycle == 10) sw_state[7] = true; // close WCLK
        if (cycle == 11) sw_state[7] = false; // open WCLK
        if (cycle == 12) sw_state[6] = false; // open WE
        if (cycle == 12) sw_state[1] = true; // close RUN
        if (cycle == 13) sw_state[0] = true; // close PCLK
        if (cycle == 14) sw_state[0] = false; // open PCLK
        if (cycle == 15) sw_state[0] = true; // close PCLK
        if (cycle == 16) sw_state[0] = false; // open PCLK
        if (cycle == 17) sw_state[0] = true; // close PCLK
        if (cycle == 18) sw_state[0] = false; // open PCLK
        if (cycle == 19) sw_state[0] = true; // close PCLK
        if (cycle == 20) sw_state[0] = false; // open PCLK
        if (cycle == 21) sw_state[0] = true; // close PCLK
        if (cycle == 22) sw_state[0] = false; // open PCLK
        m0_wrote = false;
        settle();
        try stdout.print("cycle {d}:", .{cycle});
        try stdout.print(" N1={d}", .{@intFromBool(high[1])});
        try stdout.print(" N2={d}", .{@intFromBool(high[2])});
        try stdout.print(" N3={d}", .{@intFromBool(high[3])});
        try stdout.print(" N4={d}", .{@intFromBool(high[4])});
        try stdout.print(" N5={d}", .{@intFromBool(high[5])});
        try stdout.print(" N6={d}", .{@intFromBool(high[6])});
        try stdout.print(" N7={d}", .{@intFromBool(high[7])});
        try stdout.print(" N8={d}", .{@intFromBool(high[8])});
        try stdout.print(" N9={d}", .{@intFromBool(high[9])});
        try stdout.print(" N10={d}", .{@intFromBool(high[10])});
        try stdout.print(" N11={d}", .{@intFromBool(high[11])});
        try stdout.print(" N12={d}", .{@intFromBool(high[12])});
        try stdout.print(" N13={d}", .{@intFromBool(high[13])});
        try stdout.print(" N14={d}", .{@intFromBool(high[14])});
        try stdout.print(" N15={d}", .{@intFromBool(high[15])});
        try stdout.print(" N16={d}", .{@intFromBool(high[16])});
        try stdout.print(" N17={d}", .{@intFromBool(high[17])});
        try stdout.print(" N18={d}", .{@intFromBool(high[18])});
        try stdout.print(" N19={d}", .{@intFromBool(high[19])});
        try stdout.print(" N20={d}", .{@intFromBool(high[20])});
        try stdout.print(" N21={d}", .{@intFromBool(high[21])});
        try stdout.print(" N22={d}", .{@intFromBool(high[22])});
        try stdout.print(" N23={d}", .{@intFromBool(high[23])});
        try stdout.print(" N24={d}", .{@intFromBool(high[24])});
        try stdout.print(" N25={d}", .{@intFromBool(high[25])});
        try stdout.print(" N26={d}", .{@intFromBool(high[26])});
        try stdout.print(" N27={d}", .{@intFromBool(high[27])});
        try stdout.print(" N28={d}", .{@intFromBool(high[28])});
        try stdout.print(" N29={d}", .{@intFromBool(high[29])});
        try stdout.print(" N30={d}", .{@intFromBool(high[30])});
        try stdout.print(" N31={d}", .{@intFromBool(high[31])});
        try stdout.print(" N32={d}", .{@intFromBool(high[32])});
        try stdout.print(" N33={d}", .{@intFromBool(high[33])});
        try stdout.print(" N34={d}", .{@intFromBool(high[34])});
        try stdout.print(" N35={d}", .{@intFromBool(high[35])});
        try stdout.print(" N36={d}", .{@intFromBool(high[36])});
        try stdout.print(" N37={d}", .{@intFromBool(high[37])});
        try stdout.print(" N38={d}", .{@intFromBool(high[38])});
        try stdout.print(" N39={d}", .{@intFromBool(high[39])});
        try stdout.print(" N40={d}", .{@intFromBool(high[40])});
        try stdout.print(" N41={d}", .{@intFromBool(high[41])});
        try stdout.print(" N42={d}", .{@intFromBool(high[42])});
        try stdout.print(" N43={d}", .{@intFromBool(high[43])});
        try stdout.print(" N44={d}", .{@intFromBool(high[44])});
        try stdout.print(" N45={d}", .{@intFromBool(high[45])});
        try stdout.print("\n", .{});
    }
}
