// Generated by Schem -- CLOCKED DIGITAL evaluation of "d_latch_seq"
// Derived from the Circuit IR; the .schem schematic is the source.
// 10 node(s), 4 relay(s), 0 memory(ies); 6 clock cycle(s).
// Sequential boolean eval, state carried across cycles (verified == the engine).
const std = @import("std");
const N: usize = 10; const NR: usize = 4; const NSE: usize = 0; const NV: usize = 1; const NS: usize = 2;
const CYCLES: usize = 6;
const vcc = [1]usize{1};
const sw_a = [2]usize{1, 1}; const sw_b = [2]usize{5, 2};
var sw_state = [NS]bool{false, false};
const r_c1 = [4]usize{2, 5, 7, 6}; const r_c2 = [4]usize{0, 0, 0, 0};
const r_com = [4]usize{1, 3, 8, 1}; const r_no = [4]usize{3, 6, 9, 8}; const r_nc = [4]usize{4, 7, 6, 10};
var energized = [_]bool{false} ** NR;
var high = [_]bool{false} ** (N + 1);

fn relax(a: usize, b: usize) bool {
    if (high[a] and !high[b] and b != 0) { high[b] = true; return true; }
    if (high[b] and !high[a] and a != 0) { high[a] = true; return true; }
    return false;
}
fn reach() void {
    for (&high) |*h| h.* = false;
    for (vcc) |v| high[v] = true;
    var changed = true;
    while (changed) {
        changed = false;
        { var e: usize = 0; while (e < NS) : (e += 1) { if (sw_state[e]) { if (relax(sw_a[e], sw_b[e])) changed = true; } } }
        { var r: usize = 0; while (r < NR) : (r += 1) {
            const t = if (energized[r]) r_no[r] else r_nc[r];
            if (relax(r_com[r], t)) changed = true;
        } }
    }
    high[0] = false;
}
fn settle() void {
    var pass: usize = 0;
    while (pass < 1000) : (pass += 1) {
        reach();
        var changed = false;
        { var r: usize = 0; while (r < NR) : (r += 1) {
            const en = high[r_c1[r]] != high[r_c2[r]];
            if (en != energized[r]) { energized[r] = en; changed = true; }
        } }
        if (!changed) break;
    }
}

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("clocked digital \"d_latch_seq\" (1=HIGH, 0=LOW), 6 cycle(s)\n", .{});
    var cycle: usize = 0;
    while (cycle < CYCLES) : (cycle += 1) {
        // timed stimulus (-events): operate the panel each cycle
        if (cycle == 0) sw_state[0] = true; // close SD
        if (cycle == 0) sw_state[1] = true; // close SC
        if (cycle == 1) sw_state[0] = false; // open SD
        if (cycle == 2) sw_state[1] = false; // open SC
        if (cycle == 3) sw_state[0] = true; // close SD
        if (cycle == 4) sw_state[1] = true; // close SC
        if (cycle == 5) sw_state[1] = false; // open SC
        if (cycle == 5) sw_state[0] = false; // open SD
        settle();
        try stdout.print("cycle {d}:", .{cycle});
        try stdout.print(" N1={d}", .{@intFromBool(high[1])});
        try stdout.print(" N2={d}", .{@intFromBool(high[2])});
        try stdout.print(" N3={d}", .{@intFromBool(high[3])});
        try stdout.print(" N4={d}", .{@intFromBool(high[4])});
        try stdout.print(" N5={d}", .{@intFromBool(high[5])});
        try stdout.print(" N6={d}", .{@intFromBool(high[6])});
        try stdout.print(" N7={d}", .{@intFromBool(high[7])});
        try stdout.print(" N8={d}", .{@intFromBool(high[8])});
        try stdout.print(" N9={d}", .{@intFromBool(high[9])});
        try stdout.print(" N10={d}", .{@intFromBool(high[10])});
        try stdout.print("\n", .{});
    }
}
