// Generated by Schem -- DC operating point of "relay_and_gate_schem"
// Derived from the Circuit IR; the .schem schematic is the source.
// 8 node(s), 2 relay(s), 0 diode(s); SZ=10 unknowns.  Build: zig run this.zig
const std = @import("std");

const N: usize = 8;
const SZ: usize = 10;
const NR: usize = 2;
const ND: usize = 0;
const RSMALL: f64 = 0.001;

const r_c1 = [2]usize{3, 4};
const r_c2 = [2]usize{0, 0};
const r_rc = [2]f64{100.0, 100.0};
const r_pu = [2]f64{0.02, 0.02};
const r_do = [2]f64{0.005, 0.005};
const r_com = [2]usize{2, 5};
const r_no = [2]usize{5, 7};
const r_nc = [2]usize{6, 8};
var energized = [_]bool{false} ** NR;

fn nv(z: []const f64, nid: usize) f64 { return if (nid == 0) 0.0 else z[nid - 1]; }
fn stampG(a: []f64, na: usize, nb: usize, g: f64) void {
    if (na != 0) a[(na - 1) * SZ + (na - 1)] += g;
    if (nb != 0) a[(nb - 1) * SZ + (nb - 1)] += g;
    if (na != 0 and nb != 0) { a[(na-1)*SZ+(nb-1)] -= g; a[(nb-1)*SZ+(na-1)] -= g; }
}
fn stampBranch(a: []f64, z: []f64, row: usize, p: usize, q: usize, emf: f64, rs: f64) void {
    if (p != 0) { a[(p-1)*SZ+row] += 1.0; a[row*SZ+(p-1)] += 1.0; }
    if (q != 0) { a[(q-1)*SZ+row] -= 1.0; a[row*SZ+(q-1)] -= 1.0; }
    if (rs != 0) a[row*SZ+row] -= rs;
    z[row] = emf;
}

fn solve(a: []f64, z: []f64, n: usize) void {
    var k: usize = 0;
    while (k < n) : (k += 1) {
        var piv = k; var best = @abs(a[k*n+k]);
        var i = k + 1;
        while (i < n) : (i += 1) { const v = @abs(a[i*n+k]); if (v > best) { best = v; piv = i; } }
        if (piv != k) {
            var c: usize = 0;
            while (c < n) : (c += 1) { const t = a[k*n+c]; a[k*n+c] = a[piv*n+c]; a[piv*n+c] = t; }
            const tz = z[k]; z[k] = z[piv]; z[piv] = tz;
        }
        const pv = a[k*n+k];
        i = k + 1;
        while (i < n) : (i += 1) {
            const f = a[i*n+k] / pv; if (f == 0) continue;
            var c: usize = k;
            while (c < n) : (c += 1) { a[i*n+c] -= f * a[k*n+c]; }
            z[i] -= f * z[k];
        }
    }
    var ii: usize = n;
    while (ii > 0) { ii -= 1; var s = z[ii]; var c: usize = ii + 1;
        while (c < n) : (c += 1) { s -= a[ii*n+c] * z[c]; } z[ii] = s / a[ii*n+ii]; }
}

var a: [SZ * SZ]f64 = undefined;
var z: [SZ]f64 = undefined;

fn assemble() void {
    for (&a) |*x| x.* = 0;
    for (&z) |*x| x.* = 0;
    { var i: usize = 0; while (i < N) : (i += 1) a[i*SZ+i] += 1e-12; }
    // base conductances (resistors, coils, closed switches, wires)
    stampG(a, 1, 3, 1000.0); // A
    stampG(a, 1, 4, 1000.0); // B
    stampG(a, 3, 0, 0.01); // KA.coil
    stampG(a, 4, 0, 0.01); // KB.coil
    stampG(a, 7, 0, 0.001); // LOAD
    // voltage-source / ideal-conductor branches
    stampBranch(a, z, 8, 1, 0, 9.0, 0.0); // BC
    stampBranch(a, z, 9, 2, 0, 12.0, 0.0); // BL
    { var r: usize = 0; while (r < NR) : (r += 1) {
        if (energized[r]) stampG(&a, r_com[r], r_no[r], 1.0 / RSMALL)
        else stampG(&a, r_com[r], r_nc[r], 1.0 / RSMALL);
    } }
}

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    var outer: usize = 0;
    while (outer < 200) : (outer += 1) {
        var newton: usize = 0;
        while (newton < 100) : (newton += 1) {
            assemble();
            solve(&a, &z, SZ);
            break;
        }
        var changed = false;
        var r: usize = 0;
        while (r < NR) : (r += 1) {
            const ic = @abs(nv(&z, r_c1[r]) - nv(&z, r_c2[r])) / r_rc[r];
            const was = energized[r];
            const now = if (was) (ic >= r_do[r]) else (ic >= r_pu[r]);
            if (now != was) { energized[r] = now; changed = true; }
        }
        if (!changed) break;
    }
    try stdout.print("DC operating point of \"relay_and_gate_schem\" (ground = 0 V)\n", .{});
    // N1 : A.a B.a BC.pos
    try stdout.print("  N{d} = {d:.4} V\n", .{ 1, z[0] });
    // N2 : BL.pos KA.com
    try stdout.print("  N{d} = {d:.4} V\n", .{ 2, z[1] });
    // N3 : A.b KA.c1
    try stdout.print("  N{d} = {d:.4} V\n", .{ 3, z[2] });
    // N4 : B.b KB.c1
    try stdout.print("  N{d} = {d:.4} V\n", .{ 4, z[3] });
    // N5 : KA.no KB.com
    try stdout.print("  N{d} = {d:.4} V\n", .{ 5, z[4] });
    // N6 : KA.nc
    try stdout.print("  N{d} = {d:.4} V\n", .{ 6, z[5] });
    // N7 : KB.no LOAD.a
    try stdout.print("  N{d} = {d:.4} V\n", .{ 7, z[6] });
    // N8 : KB.nc
    try stdout.print("  N{d} = {d:.4} V\n", .{ 8, z[7] });
}
