// Generated by Schem -- TRANSIENT analysis of "relay_oscillator_schem"
// Derived from the Circuit IR; the .schem schematic is the source.
// 3 node(s); dt=0.001 s, 12 steps.  Build: zig run this.zig
const std = @import("std");
const N: usize = 3;
const SZ: usize = 4;
const DT: f64 = 0.001;
const NSTEPS: usize = 12;
const RSMALL: f64 = 0.001;
const NR: usize = 1; const ND: usize = 0; const NC: usize = 0; const NL: usize = 0; const NK: usize = 0;

const r_c1 = [1]usize{2}; const r_c2 = [1]usize{0}; const r_rc = [1]f64{100.0};
const r_pu = [1]f64{0.05}; const r_do = [1]f64{0.005}; const r_dl = [1]f64{0.0};
const r_com = [1]usize{1}; const r_no = [1]usize{3}; const r_nc = [1]usize{2};
const r_ci = [1]i64{-1};
var energized = [_]bool{false} ** NR;
var pend_t = [_]bool{false} ** NR;   // pending target
var pend_s = [_]f64{0} ** NR;        // time the pending move began

fn nv(z: []const f64, nid: usize) f64 { return if (nid == 0) 0.0 else z[nid - 1]; }
fn stampG(a: []f64, na: usize, nb: usize, g: f64) void {
    if (na != 0) a[(na-1)*SZ+(na-1)] += g;
    if (nb != 0) a[(nb-1)*SZ+(nb-1)] += g;
    if (na != 0 and nb != 0) { a[(na-1)*SZ+(nb-1)] -= g; a[(nb-1)*SZ+(na-1)] -= g; }
}
fn stampI(z: []f64, na: usize, nb: usize, i: f64) void {
    if (na != 0) z[na-1] -= i;
    if (nb != 0) z[nb-1] += i;
}
fn stampBranch(a: []f64, z: []f64, row: usize, p: usize, q: usize, emf: f64, rs: f64) void {
    if (p != 0) { a[(p-1)*SZ+row] += 1.0; a[row*SZ+(p-1)] += 1.0; }
    if (q != 0) { a[(q-1)*SZ+row] -= 1.0; a[row*SZ+(q-1)] -= 1.0; }
    if (rs != 0) a[row*SZ+row] -= rs;
    z[row] = emf;
}
fn solve(a: []f64, z: []f64, n: usize) void {
    var k: usize = 0;
    while (k < n) : (k += 1) {
        var piv = k; var best = @abs(a[k*n+k]); var i = k + 1;
        while (i < n) : (i += 1) { const v = @abs(a[i*n+k]); if (v > best) { best = v; piv = i; } }
        if (piv != k) { var c: usize = 0; while (c < n) : (c += 1) { const t = a[k*n+c]; a[k*n+c] = a[piv*n+c]; a[piv*n+c] = t; } const tz = z[k]; z[k] = z[piv]; z[piv] = tz; }
        const pv = a[k*n+k]; i = k + 1;
        while (i < n) : (i += 1) { const f = a[i*n+k] / pv; if (f == 0) continue; var c: usize = k; while (c < n) : (c += 1) { a[i*n+c] -= f * a[k*n+c]; } z[i] -= f * z[k]; }
    }
    var ii: usize = n;
    while (ii > 0) { ii -= 1; var s = z[ii]; var c: usize = ii + 1; while (c < n) : (c += 1) { s -= a[ii*n+c] * z[c]; } z[ii] = s / a[ii*n+ii]; }
}

fn assemble(a: []f64, z: []f64) void {
    for (a) |*x| x.* = 0; for (z) |*x| x.* = 0;
    { var i: usize = 0; while (i < N) : (i += 1) a[i*SZ+i] += 1e-12; }
    stampG(a, 2, 0, 0.01); // K.coil
    stampBranch(a, z, 3, 1, 0, 12.0, 0.0); // B
    { var r: usize = 0; while (r < NR) : (r += 1) {
        if (energized[r]) stampG(a, r_com[r], r_no[r], 1.0/RSMALL) else stampG(a, r_com[r], r_nc[r], 1.0/RSMALL);
    } }
}

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    var a = [_]f64{0} ** (SZ * SZ);
    var z = [_]f64{0} ** SZ;
    try stdout.print("transient \"relay_oscillator_schem\"  (t, then N1..N3)\n", .{});
    var step: usize = 0;
    while (step <= NSTEPS) : (step += 1) {
        const tnow = @as(f64, @floatFromInt(step)) * DT;
        // Newton (diodes) at this step; relay state is from the previous step.
        var newton: usize = 0;
        while (newton < 100) : (newton += 1) {
            assemble(a[0..], z[0..]); solve(a[0..], z[0..], SZ);
            break;
        }
        try stdout.print("{d:.5}", .{tnow});
        try stdout.print(" {d:.4}", .{ z[0] });
        try stdout.print(" {d:.4}", .{ z[1] });
        try stdout.print(" {d:.4}", .{ z[2] });
        try stdout.print("\n", .{});
        { var r: usize = 0; while (r < NR) : (r += 1) {
            var ic: f64 = undefined;
            ic = @abs(nv(z[0..], r_c1[r]) - nv(z[0..], r_c2[r])) / r_rc[r];
            const was = energized[r];
            const now = if (was) (ic >= r_do[r]) else (ic >= r_pu[r]);
            if (now == was) { pend_t[r] = was; }
            else if (r_dl[r] <= 0) { energized[r] = now; }
            else {
                if (pend_t[r] != now) { pend_t[r] = now; pend_s[r] = tnow; }
                if (tnow - pend_s[r] >= r_dl[r]) energized[r] = now;
            }
        } }
    }
}
