// Generated by Schem -- DC operating point of "voltage_divider_schem"
// Derived from the Circuit IR; the .schem schematic is the source.
// 2 node(s) + 1 branch(es) = 3 unknown(s).  Build: zig run this.zig
const std = @import("std");

const N: usize = 2;        // non-ground nodes
const SZ: usize = 3;       // + source/conductor branches

// Gaussian elimination with partial pivoting (A x = z; result in z).
fn solve(a: []f64, z: []f64, n: usize) void {
    var k: usize = 0;
    while (k < n) : (k += 1) {
        var piv = k;
        var best = @abs(a[k * n + k]);
        var i = k + 1;
        while (i < n) : (i += 1) {
            const v = @abs(a[i * n + k]);
            if (v > best) { best = v; piv = i; }
        }
        if (piv != k) {
            var c: usize = 0;
            while (c < n) : (c += 1) {
                const t = a[k * n + c]; a[k * n + c] = a[piv * n + c]; a[piv * n + c] = t;
            }
            const tz = z[k]; z[k] = z[piv]; z[piv] = tz;
        }
        const pv = a[k * n + k];
        i = k + 1;
        while (i < n) : (i += 1) {
            const f = a[i * n + k] / pv;
            if (f == 0) continue;
            var c: usize = k;
            while (c < n) : (c += 1) { a[i * n + c] -= f * a[k * n + c]; }
            z[i] -= f * z[k];
        }
    }
    var ii: usize = n;
    while (ii > 0) {
        ii -= 1;
        var s = z[ii];
        var c: usize = ii + 1;
        while (c < n) : (c += 1) { s -= a[ii * n + c] * z[c]; }
        z[ii] = s / a[ii * n + ii];
    }
}

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    var a = [_]f64{0} ** (SZ * SZ);
    var z = [_]f64{0} ** SZ;

    // gmin: a tiny conductance to ground keeps the system non-singular.
    { var i: usize = 0; while (i < N) : (i += 1) { a[i * SZ + i] += 1e-12; } }

    // conductances (Ohm's law)
    // R1 (resistor)
    a[0 * SZ + 0] += 0.001;
    a[1 * SZ + 1] += 0.001;
    a[0 * SZ + 1] -= 0.001;
    a[1 * SZ + 0] -= 0.001;
    // R2 (resistor)
    a[1 * SZ + 1] += 0.0005;
    // voltage-source / ideal-conductor branches
    // branch B  (row 2)
    a[0 * SZ + 2] += 1.0;
    a[2 * SZ + 0] += 1.0;
    z[2] = 9.0;

    solve(a[0..], z[0..], SZ);

    try stdout.print("DC operating point of \"voltage_divider_schem\" (ground = 0 V)\n", .{});
    // N1 : B.pos R1.a
    try stdout.print("  N{d} = {d:.4} V\n", .{ 1, z[0] });
    // N2 : R1.b R2.a
    try stdout.print("  N{d} = {d:.4} V\n", .{ 2, z[1] });
}
