// Generated by Schem -- DC operating point of "voltage_divider_schem"
// Derived from the Circuit IR; the .schem schematic is the source.
// 2 node(s), 0 relay(s), 0 diode(s); SZ=3 unknowns.  Build: zig run this.zig
const std = @import("std");

const N: usize = 2;
const SZ: usize = 3;
const NR: usize = 0;
const ND: usize = 0;
const RSMALL: f64 = 0.001;


fn nv(z: []const f64, nid: usize) f64 { return if (nid == 0) 0.0 else z[nid - 1]; }
fn stampG(a: []f64, na: usize, nb: usize, g: f64) void {
    if (na != 0) a[(na - 1) * SZ + (na - 1)] += g;
    if (nb != 0) a[(nb - 1) * SZ + (nb - 1)] += g;
    if (na != 0 and nb != 0) { a[(na-1)*SZ+(nb-1)] -= g; a[(nb-1)*SZ+(na-1)] -= g; }
}
fn stampBranch(a: []f64, z: []f64, row: usize, p: usize, q: usize, emf: f64, rs: f64) void {
    if (p != 0) { a[(p-1)*SZ+row] += 1.0; a[row*SZ+(p-1)] += 1.0; }
    if (q != 0) { a[(q-1)*SZ+row] -= 1.0; a[row*SZ+(q-1)] -= 1.0; }
    if (rs != 0) a[row*SZ+row] -= rs;
    z[row] = emf;
}

fn solve(a: []f64, z: []f64, n: usize) void {
    var k: usize = 0;
    while (k < n) : (k += 1) {
        var piv = k; var best = @abs(a[k*n+k]);
        var i = k + 1;
        while (i < n) : (i += 1) { const v = @abs(a[i*n+k]); if (v > best) { best = v; piv = i; } }
        if (piv != k) {
            var c: usize = 0;
            while (c < n) : (c += 1) { const t = a[k*n+c]; a[k*n+c] = a[piv*n+c]; a[piv*n+c] = t; }
            const tz = z[k]; z[k] = z[piv]; z[piv] = tz;
        }
        const pv = a[k*n+k];
        i = k + 1;
        while (i < n) : (i += 1) {
            const f = a[i*n+k] / pv; if (f == 0) continue;
            var c: usize = k;
            while (c < n) : (c += 1) { a[i*n+c] -= f * a[k*n+c]; }
            z[i] -= f * z[k];
        }
    }
    var ii: usize = n;
    while (ii > 0) { ii -= 1; var s = z[ii]; var c: usize = ii + 1;
        while (c < n) : (c += 1) { s -= a[ii*n+c] * z[c]; } z[ii] = s / a[ii*n+ii]; }
}

fn assemble(a: []f64, z: []f64) void {
    for (a) |*x| x.* = 0;
    for (z) |*x| x.* = 0;
    { var i: usize = 0; while (i < N) : (i += 1) a[i*SZ+i] += 1e-12; }
    // base conductances (resistors, coils, closed switches, wires)
    stampG(a, 1, 2, 0.001); // R1
    stampG(a, 2, 0, 0.0005); // R2
    // voltage-source / ideal-conductor branches
    stampBranch(a, z, 2, 1, 0, 9.0, 0.0); // B
}

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    var a = [_]f64{0} ** (SZ * SZ);
    var z = [_]f64{0} ** SZ;
    var outer: usize = 0;
    while (outer < 200) : (outer += 1) {
        var newton: usize = 0;
        while (newton < 100) : (newton += 1) {
            assemble(a[0..], z[0..]);
            solve(a[0..], z[0..], SZ);
            break;
        }
        break;
    }
    try stdout.print("DC operating point of \"voltage_divider_schem\" (ground = 0 V)\n", .{});
    // N1 : B.pos R1.a
    try stdout.print("  N{d} = {d:.4} V\n", .{ 1, z[0] });
    // N2 : R1.b R2.a
    try stdout.print("  N{d} = {d:.4} V\n", .{ 2, z[1] });
}
