# lib/bombe_zig.tcl --
#
# Emit the bombe's 26^3 position scan as a self-contained Zig program -- the
# heavy sweep, compiled rather than interpreted (the project's chosen path for
# the search loop).  The generated program embeds the Wehrmacht rotor windings,
# the reflector, the menu (crib graph) and the ring setting, then for every
# rotor start position it:
#   * steps a faithful Enigma from that start to set each scrambler's position,
#   * builds the scrambler permutations,
#   * unions the menu's scrambler edges and Welchman's diagonal board, and
#   * reports a STOP when the test register collapses to a single live (or
#     single dead) wire -- exactly the Tcl model in lib/bombe.tcl, so the two
#     must agree.
#
# Usage:  set zig [::bombe::emitZig $edges $wheels $rings $reflector $test]
#         writes a *.zig you run with `zig run bombe.zig`.

package require Tcl 8.6-
namespace eval ::bombe {}

proc ::bombe::EmitWirings {} {
    variable ::enigma::ROTOR ; variable ::enigma::REFLECTOR
    set out ""
    foreach r {I II III IV V} {
        append out "    \"[dict get $::enigma::ROTOR($r) wiring]\".*,\n"
    }
    return $out
}

# emitZig -- generate the scanner.  `edges` is the menu (from ::bombe::menu),
# `test` the central letter.  Wheel order, rings and reflector are baked in.
proc ::bombe::emitZig {edges wheels rings reflector {test ""}} {
    if {$test eq ""} { set test [::bombe::central $edges] }
    set letters [::bombe::letters $edges]
    set nL [llength $letters]
    # letter -> menu-local cable index
    set idx [dict create] ; set k 0
    foreach l $letters { dict set idx $l $k ; incr k }

    variable ::enigma::ROTOR ; variable ::enigma::REFLECTOR
    lassign $wheels wL wM wR
    lassign [::enigma::triple $rings] rL rM rR
    set wlL [dict get $::enigma::ROTOR($wL) wiring]
    set wlM [dict get $::enigma::ROTOR($wM) wiring]
    set wlR [dict get $::enigma::ROTOR($wR) wiring]
    set nlL [::enigma::ord [dict get $::enigma::ROTOR($wL) notch]]
    set nlM [::enigma::ord [dict get $::enigma::ROTOR($wM) notch]]
    set nlR [::enigma::ord [dict get $::enigma::ROTOR($wR) notch]]
    set refl $::enigma::REFLECTOR($reflector)

    # Menu edges as {offset cableA cableB} with cable indices.
    set edgeRows {}
    set maxoff 0
    foreach e $edges {
        lassign $e off a b
        if {$off > $maxoff} { set maxoff $off }
        lappend edgeRows "        .{ .off = $off, .a = [dict get $idx $a], .b = [dict get $idx $b] },"
    }
    # Letter ordinals for the diagonal board (cable index -> alphabet ordinal).
    set ords {}
    foreach l $letters { lappend ords [::enigma::ord $l] }

    set testIdx [dict get $idx $test]
    set testWire [::enigma::ord $test]

    set E "\n"
    set src ""
    append src "// Bombe scan -- generated by Schem (lib/bombe_zig.tcl).$E"
    append src "// Wheel order $wheels, rings $rings, reflector $reflector.$E"
    append src "// Menu test letter '$test'.  Build: zig run this.zig$E$E"
    append src "const std = @import(\"std\");$E$E"

    append src "const NL: usize = $nL;        // cables in the menu$E"
    append src "const MAXOFF: usize = $maxoff;$E"
    append src "const TEST: usize = $testIdx;     // central cable index$E"
    append src "const TEST_WIRE: usize = $testWire;$E$E"

    append src "const wlL = \"$wlL\".*;$E"
    append src "const wlM = \"$wlM\".*;$E"
    append src "const wlR = \"$wlR\".*;$E"
    append src "const refl = \"$refl\".*;$E"
    append src "const rL: usize = $rL; const rM: usize = $rM; const rR: usize = $rR;$E"
    append src "const nL: usize = $nlL; const nM: usize = $nlM; const nR: usize = $nlR;$E$E"

    append src "const Edge = struct { off: usize, a: usize, b: usize };$E"
    append src "const edges = \[_\]Edge{$E"
    append src [join $edgeRows $E]
    append src "$E};$E$E"

    append src "const ords = \[NL\]usize{ [join $ords {, }] };$E$E"

    append src {fn ord(c: u8) usize { return @as(usize, c - 'A'); }
fn inv(w: [26]u8, out: *[26]usize) void {
    var i: usize = 0; while (i < 26) : (i += 1) out[ord(w[i])] = i;
}

// one rotor pass; dir=true forward (use wiring), false reverse (use inverse)
fn pass(wf: [26]u8, wi: [26]usize, p: usize, r: usize, s: usize, fwd: bool) usize {
    const x = (s + p + 26 - r) % 26;
    const y = if (fwd) ord(wf[x]) else wi[x];
    return (y + 26 + r - p) % 26;
}

// the scrambler permutation at rotor position (pL,pM,pR)
fn scrambler(pL: usize, pM: usize, pR: usize,
             ivL: [26]usize, ivM: [26]usize, ivR: [26]usize, out: *[26]usize) void {
    var s: usize = 0;
    while (s < 26) : (s += 1) {
        var x = pass(wlR, ivR, pR, rR, s, true);
        x = pass(wlM, ivM, pM, rM, x, true);
        x = pass(wlL, ivL, pL, rL, x, true);
        x = ord(refl[x]);
        x = pass(wlL, ivL, pL, rL, x, false);
        x = pass(wlM, ivM, pM, rM, x, false);
        x = pass(wlR, ivR, pR, rR, x, false);
        out[s] = x;
    }
}

// union-find over NL*26 nodes
var parent: [NL * 26]usize = undefined;
fn find(start: usize) usize {
    var i = start;
    while (parent[i] != i) { parent[i] = parent[parent[i]]; i = parent[i]; }
    return i;
}
fn unite(a: usize, b: usize) void {
    const ra = find(a); const rb = find(b);
    if (ra != rb) parent[ra] = rb;
}
}
    append src $E
    append src {pub fn main() !void {
    const stdout = std.io.getStdOut().writer();

    // rotor inverses (fixed; rings/positions handled in pass)
    var ivL: [26]usize = undefined; var ivM: [26]usize = undefined; var ivR: [26]usize = undefined;
    inv(wlL, &ivL); inv(wlM, &ivM); inv(wlR, &ivR);

    var hits: usize = 0;
    var L: usize = 0;
    while (L < 26) : (L += 1) {
        var M: usize = 0;
        while (M < 26) : (M += 1) {
            var R: usize = 0;
            while (R < 26) : (R += 1) {
                // Step the machine from this ground to each offset's position,
                // honouring middle/left turnover and the double step.
                var posL: [MAXOFF + 1]usize = undefined;
                var posM: [MAXOFF + 1]usize = undefined;
                var posR: [MAXOFF + 1]usize = undefined;
                var cL = L; var cM = M; var cR = R;
                var off: usize = 0;
                while (off <= MAXOFF) : (off += 1) {
                    // stepping precedes the character
                    const midAtNotch = (cM == nM);
                    const rightAtNotch = (cR == nR);
                    if (midAtNotch) { cM = (cM + 1) % 26; cL = (cL + 1) % 26; }
                    else if (rightAtNotch) { cM = (cM + 1) % 26; }
                    cR = (cR + 1) % 26;
                    posL[off] = cL; posM[off] = cM; posR[off] = cR;
                }

                // reset union-find
                var i: usize = 0;
                while (i < NL * 26) : (i += 1) parent[i] = i;

                // scrambler edges
                for (edges) |e| {
                    var perm: [26]usize = undefined;
                    scrambler(posL[e.off], posM[e.off], posR[e.off], ivL, ivM, ivR, &perm);
                    var w: usize = 0;
                    while (w < 26) : (w += 1) {
                        unite(e.a * 26 + w, e.b * 26 + perm[w]);
                    }
                }
                // Welchman diagonal board
                var a: usize = 0;
                while (a < NL) : (a += 1) {
                    var b: usize = a + 1;
                    while (b < NL) : (b += 1) {
                        unite(a * 26 + ords[b], b * 26 + ords[a]);
                    }
                }

                // read the test register
                const root = find(TEST * 26 + TEST_WIRE);
                var live: usize = 0; var lastLive: usize = 0; var lastDead: usize = 0;
                var w: usize = 0;
                while (w < 26) : (w += 1) {
                    if (find(TEST * 26 + w) == root) { live += 1; lastLive = w; }
                    else lastDead = w;
                }
                if (live == 1 or live == 25) {
                    const stecker = if (live == 1) lastLive else lastDead;
                    hits += 1;
                    try stdout.print("STOP {c}{c}{c} -> stecker {c}\n", .{
                        @as(u8, @intCast('A' + L)), @as(u8, @intCast('A' + M)),
                        @as(u8, @intCast('A' + R)), @as(u8, @intCast('A' + stecker)),
                    });
                }
            }
        }
    }
    try stdout.print("{d} stop(s) over 17576 positions\n", .{hits});
}
}
    return $src
}

package provide bombe_zig 1.0
